### ISSUE TITLE
Exception while starting Elasticsearch

### ISSUE THREAD

**Issue by rlueckl** [opendistro-for-elasticsearch/performance-analyzer#54]
Hi,

I get the following exception every time when starting my Open Distro Elasticsearch nodes:

```
[2019-06-05T12:56:24,350][ERROR][c.a.o.e.p.o.OSGlobals    ] [hostname.censored] Error in reading/parsing clk.tck value: java.lang.NumberFormatException: null
java.lang.NumberFormatException: null
	at java.lang.Long.parseUnsignedLong(Long.java:680) ~[?:1.8.0_212]
	at java.lang.Long.parseUnsignedLong(Long.java:746) ~[?:1.8.0_212]
	at com.amazon.opendistro.elasticsearch.performanceanalyzer.os.OSGlobals.getScClkTckFromConfig(OSGlobals.java:65) ~[?:?]
	at com.amazon.opendistro.elasticsearch.performanceanalyzer.os.OSGlobals.<clinit>(OSGlobals.java:43) ~[?:?]
	at com.amazon.opendistro.elasticsearch.performanceanalyzer.hwnet.NetworkE2E.<clinit>(NetworkE2E.java:47) ~[?:?]
	at com.amazon.opendistro.elasticsearch.performanceanalyzer.metrics_generator.linux.LinuxOSMetricsGenerator.getTCPMetricsGenerator(LinuxOSMetricsGenerator.java:79) ~[?:?]
	at com.amazon.opendistro.elasticsearch.performanceanalyzer.collectors.NetworkE2ECollector.collectMetrics(NetworkE2ECollector.java:37) ~[?:?]
	at com.amazon.opendistro.elasticsearch.performanceanalyzer.collectors.PerformanceAnalyzerMetricsCollector.lambda$run$0(PerformanceAnalyzerMetricsCollector.java:57) ~[?:?]
	at com.amazon.opendistro.elasticsearch.performanceanalyzer.PerformanceAnalyzerPlugin.lambda$invokePrivileged$1(PerformanceAnalyzerPlugin.java:106) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_212]
	at com.amazon.opendistro.elasticsearch.performanceanalyzer.PerformanceAnalyzerPlugin.invokePrivileged(PerformanceAnalyzerPlugin.java:104) [opendistro_performance_analyzer-0.9.0.0.jar:0.9.0.0]
	at com.amazon.opendistro.elasticsearch.performanceanalyzer.collectors.PerformanceAnalyzerMetricsCollector.run(PerformanceAnalyzerMetricsCollector.java:57) [opendistro_performance_analyzer-0.9.0.0.jar:0.9.0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

I have the following installed:
 * opendistroforelasticsearch 0.9.0.0-1 (incl. opendistro-performance-analyzer 0.9.0.0-1)
 * elasticsearch-oss 6.7.1
 * AdoptOpenJDK 8u212
 * Debian Stretch 9.9

I've also linked "tools.jar", as written in the documentation here in *Step 5*: https://opendistro.github.io/for-elasticsearch-docs/docs/install/rpm/ (I know, this is for RPM, but without linking it wouldn't even start on Debian)

```
$ readlink -f /usr/share/elasticsearch/lib/tools.jar 
/usr/lib/jvm/adoptopenjdk-8-hotspot-amd64/lib/tools.jar
```

The cluster seems to work fine - at least I didn't notice any problems. But still, it'd be good to know what this exception means and how I could fix it (going to AdoptOpenJDK 11 isn't an option because of other issues in our setup).

**Comment by ditac** [comment]
You need to set the following parameters before starting Elasticsearch, so that the Performance Analyzer plugin has the necessary privileges to gather OS statistics.

if ! grep -q '## OpenDistro Performance Analyzer' /etc/elasticsearch/jvm.options; then
   CLK_TCK=`/usr/bin/getconf CLK_TCK`
   echo >> /etc/elasticsearch/jvm.options
   echo '## OpenDistro Performance Analyzer' >> /etc/elasticsearch/jvm.options
   echo "-Dclk.tck=$CLK_TCK" >> /etc/elasticsearch/jvm.options
   echo "-Djdk.attach.allowAttachSelf=true" >> /etc/elasticsearch/jvm.options
   echo "-Djava.security.policy=file:///usr/share/elasticsearch/plugins/opendistro_performance_analyzer/pa_config/es_security.policy" >> /etc/elasticsearch/jvm.options
fi

From your stack trace it looks like the right CLK_TCK value is not being passed to Elasticsearch.

**Comment by rlueckl** [comment]
Hi @ditac,

thank you for the help! The missing parameters were the issue. I've added them and the exception went away.

**Comment by yinrong** [comment]
FROM amazon/opendistro-for-elasticsearch:1.6.0

I'm using official image, still got this error. going to remove this plugin
